server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${user.home}/config-repo/{application}/{profile}/
security:
  user:
    password: messwiththebest
    name: root
