info:
  description: CAS Configuration

cas:
  server:
    name: https://cas:8443
    prefix: https://cas:8443/cas
  adminPagesSecurity:
    ip: 127\.0\.0\.1

# mongo as service registry
# see: https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#mongodb-service-registry
  serviceRegistry:
    mongo:
      host: mongodb
      databaseName: cas
      collectionName: cas-service-registry

logging:
  config: classpath:config/log4j2.xml


