package de.example.mybatis.model;

import java.util.Date;

public class Ad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.company_id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.company_categ_id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    private Long companyCategId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ad_mobile_image
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    private String adMobileImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.created_at
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.updated_at
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.ad_gps
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    private byte[] adGps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.id
     *
     * @return the value of ad.id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.id
     *
     * @param id the value for ad.id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.company_id
     *
     * @return the value of ad.company_id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.company_id
     *
     * @param companyId the value for ad.company_id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.company_categ_id
     *
     * @return the value of ad.company_categ_id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public Long getCompanyCategId() {
        return companyCategId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.company_categ_id
     *
     * @param companyCategId the value for ad.company_categ_id
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public void setCompanyCategId(Long companyCategId) {
        this.companyCategId = companyCategId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ad_mobile_image
     *
     * @return the value of ad.ad_mobile_image
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public String getAdMobileImage() {
        return adMobileImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ad_mobile_image
     *
     * @param adMobileImage the value for ad.ad_mobile_image
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public void setAdMobileImage(String adMobileImage) {
        this.adMobileImage = adMobileImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.created_at
     *
     * @return the value of ad.created_at
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.created_at
     *
     * @param createdAt the value for ad.created_at
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.updated_at
     *
     * @return the value of ad.updated_at
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.updated_at
     *
     * @param updatedAt the value for ad.updated_at
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.ad_gps
     *
     * @return the value of ad.ad_gps
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public byte[] getAdGps() {
        return adGps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.ad_gps
     *
     * @param adGps the value for ad.ad_gps
     *
     * @mbggenerated Thu Mar 19 18:05:44 CET 2015
     */
    public void setAdGps(byte[] adGps) {
        this.adGps = adGps;
    }
}