logging:
  level:
    org:
      springframework: info
    ROOT: info

spring:
  main:
    banner-mode: "off"
  cloud:
    stream:
      bindings:
        output:
          binder: kafka
          destination: test
          contentType: ""
          headerMode: raw
      instanceCount: 1
      instanceIndex: 0
      kafka:
        binder:
          zkNodes: "kafka:2181"
          brokers: "kafka:9092,kafka:9093,kafka:9094"
          autoCreateTopics: true

# Health indicator for binders.
management:
  health:
    binders:
      enabled: true


# ME QUEDA 7.3 Partitioning
# Y OPCIONES A MOGOLLÓN EN 12.3 Configuration Options
