# Spring Boot configuration properties
spring:
  application:
    name: spring-sqs-server
  main:
    banner-mode: "LOG"

server:
  port: 8080

# By default Spring Boot uses logback.
# logging:
#   level:
#     org:
#       springframework: info
#     ROOT: info
   
# Using log4j2 (just for fun) It requires exclusions in spring-boot-starter because by default
# Spring Boot will pick up the logback dependency :/
logging:
  config: classpath:log4j2.xml
 

# AWS
cloud:
  aws:
    credentials:
      # Two options:
      # 1- Declaring keys:
      accessKey: ${AWS_ACCES_KEY}
      secretKey: ${AWS_SECRET_KEY}
      # 2- Given some IAM role to the AWS instance where this app will be running.
      # AWS SDK used by Spring will retrieve the credentials from http://169.254.169.254/latest/meta-data/iam/security-credentials/
      # cloud.aws.credentials.instanceProfile: true
    region:
      # When no running in AWS environment automatic region detection crashes application
      auto: false
      static: eu-west-1
      
app:
  aws:
    sqs:
      queue-name: ${AWS_SQS_QUEUE_NAME}
