# Spring Boot configuration properties
spring:
  application:
    name: web-services-spring-rest-server
  main:
    banner-mode: "LOG"

datasources:
  locations:
    jdbcUrl: jdbc:postgresql://localhost:5432/locations
    username: locations
    password: locations
    driver-class-name: org.postgresql.Driver
    max-wait: 10000
    max-active: 50
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1
  conciliation:
    jdbcUrl: jdbc:postgresql://localhost:5433/conciliation
    username: conciliation
    password: conciliation
    driver-class-name: org.postgresql.Driver
    max-wait: 10000
    max-active: 50
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml


server:
  port: 8080

management:
  security:
    enabled: true
    roles: SUPERUSER
  health:
    # In this way we can enable just the health checks that we want.
    defaults:
      enabled: false
    # Just enable my custom health check
    custom:
      enabled: true
  info:
    # In this way we can enable just the information that we want.
    defaults:
      enabled: false
    # Enabling git information
    git:
      enabled: true
      mode: FULL
    # Enabling build information
    build:
      enabled: true
    # Enabling my custom information
    custom:
      enabled: true
  # Removing usless X-Application-Context HTTP header.
  # It contains the application's name (I do not need it right now)
  add-application-context-header: false
endpoints:
  sensitive: true
  health:
    sensitive: false
    time-to-live: 2000
security:
  user:
    name: admin
    password: admin

springfox.documentation.swagger.v2.path: /schema

# By default Spring Boot uses logback.
# logging:
#   level:
#     org:
#       springframework: info
#     ROOT: info
   
# Using log4j2 (just for fun) It requires exclusions in spring-boot-starter because by default
# Spring Boot will pick up the logback dependency :/
logging:
  config: classpath:log4j2.xml
