# Spring Boot configuration properties
spring:
  application:
    name: spring-sns-client
  main:
    banner-mode: "LOG"
    # We do not need Tomcat running (this application runs from console)
    web-environment: false
  
# By default Spring Boot uses logback.
# logging:
#   level:
#     org:
#       springframework: info
#     ROOT: info
   
# Using log4j2 (just for fun) It requires exclusions in spring-boot-starter because by default
# Spring Boot will pick up the logback dependency :/
logging:
  config: classpath:log4j2.xml
  
# AWS
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCES_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      auto: false
      static: eu-west-1
      
# Application properties
app:
  aws:
    sns:
      # example: arn:aws:sns:eu-west-1:269641089515:gus-sns-topic
      topic-arn: ${AWS_SNS_ARN}
