INSERT INTO LOCATION (DESCRIPTION, PARENT_ID) VALUES
('Root', 1)
,('Spain', 1)
,('Barcelona', 2)
,('Avila', 2)
,('Toledo', 2)
,('Sant Cugat', 3)
,('Alcorcon', 2)
,('Candeleda', 4)
,('Arenas de San Pedro', 4)
,('Home', 6)
,('Second Home', 8)
,('Portugal', 1)
,('Oporto', 12)
,('Lisboa', 12)
,('Moreira', 14);


INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID) VALUES
('1', '1', '0')
,('2', '2', '0')
,('3', '3', '0')
,('4', '4', '0')
,('5', '5', '0')
,('6', '6', '0')
,('7', '7', '0')
,('8', '8', '0')
,('9', '9', '0')
,('10', '10', '0')
,('11', '11', '0')
,('12', '12', '0')
,('13', '13', '0')
,('14', '14', '0')
,('15', '15', '0');


-- Spain belongs to Root
-- Spain LOCATION: 2
-- Root LOCATION: 1
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 1
	AND CS.PARENT_ID = 2;


-- Portugal belongs to Root
-- Portugal LOCATION: 12
-- Root LOCATION: 1
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 1
	AND CS.PARENT_ID = 12;
	

-- Barcelona belongs to Spain
-- Barcelona LOCATION: 3
-- Spain LOCATION: 2
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 2
	AND CS.PARENT_ID = 3;
	

-- Avila belongs to Spain
-- Avila LOCATION: 4
-- Spain LOCATION: 2
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 2
	AND CS.PARENT_ID = 4;

	
-- Making Sant Cugat a child of Barcelona and grand child of Spain
-- Sant Cugat LOCATION: 6
-- Barcelona LOCATION: 3
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 3
	AND CS.PARENT_ID = 6;
	
	
-- Making Candeleda a child of Avila and grand child of Spain
-- Candeleda LOCATION: 8
-- Avila LOCATION: 4
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 4
	AND CS.PARENT_ID = 8;
	
	
-- Making Home a child of Sant Cugat and grand child of Barcelona and grand grand child of Spain
-- Sant Cugat LOCATION: 6
-- Home LOCATION: 10
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 6
	AND CS.PARENT_ID = 10;
	

-- Making Second Home a child of Candeleda and grand child of Avila and grand grand child of Spain
-- Candeleda LOCATION: 8
-- Second Home LOCATION: 11
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 8
	AND CS.PARENT_ID = 11;


-- Oporto belongs to Portugal
-- Oporto LOCATION: 13
-- Portugal LOCATION: 12
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 12
	AND CS.PARENT_ID = 13;
	

-- Lisboa belongs to Portugal
-- Lisboa LOCATION: 14
-- Portugal LOCATION: 12
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
	CF.PARENT_ID,
	CS.CHILD_ID,
	(CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
	CF.CHILD_ID = 12
	AND CS.PARENT_ID = 14;


-- Making Moreira a child of Oporto and grand child of Portugal
-- Moreria LOCATION: 15
-- Oporto LOCATION: 13
INSERT INTO LOCATION_HIERARCHY (PARENT_ID, CHILD_ID, LEVEL_ID)
SELECT
    CF.PARENT_ID,
    CS.CHILD_ID,
    (CF.LEVEL_ID + (CS.LEVEL_ID + 1))
FROM LOCATION_HIERARCHY CF, LOCATION_HIERARCHY CS
WHERE
    CF.CHILD_ID = 13
    AND CS.PARENT_ID = 15;