logging:
  level:
    org:
      springframework: info
    ROOT: info

spring:
  main:
    banner-mode: "off"

kafka:
  topic: test
  messageKey: keyTest



# *************************** BINDERS CONFIGURATION ***************************
spring:
  cloud:
    stream:
      bindings:
        input:
          binder: kafka
          destination: test
          group: helloworld
          contentType: ""
          consumer:
            concurrency: 1
            partitioned: false
            headerMode: raw
            maxAttempts: 3
            backOffInitialInterval:
      instanceCount: 1
      instanceIndex: 0
      kafka:
        binder:
          brokers: "kafka:9092,kafka:9093,kafka:9094"
          autoCreateTopics: true

# Health indicator for binders.
management:
  health:
    binders:
      enabled: true

# ME QUEDA 7.3 Partitioning
# Y OPCIONES A MOGOLLÓN EN 12.3 Configuration Options
