package de.example.exampletdd.model.forecastweather;

import java.io.Serializable;
import java.util.List;

/**
 * Auto generated by: http://jsongen.byingtondesign.com/
 * (with my own modifications)
 * 
 */
public class ForecastWeatherData implements Serializable {
    private static final long serialVersionUID = 5095443678019686190L;
    private City city;
    private Number cnt;
    private Number cod;
    private List<de.example.exampletdd.model.forecastweather.List> list;
    private Number message;

    public City getCity(){
        return this.city;
    }
    public void setCity(final City city){
        this.city = city;
    }
    public Number getCnt(){
        return this.cnt;
    }
    public void setCnt(final Number cnt){
        this.cnt = cnt;
    }

    public Number getCod() {
        return this.cod;
    }

    public void setCod(final Number cod) {
        this.cod = cod;
    }

    public List<de.example.exampletdd.model.forecastweather.List> getList() {
        return this.list;
    }

    public void setList(final List<de.example.exampletdd.model.forecastweather.List> list) {
        this.list = list;
    }
    public Number getMessage(){
        return this.message;
    }
    public void setMessage(final Number message){
        this.message = message;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append("ForecastWeatherData [city=").append(this.city).append(", cnt=")
        .append(this.cnt).append(", cod=").append(this.cod).append(", list=")
        .append(this.list).append(", message=").append(this.message).append("]");
        return builder.toString();
    }
}
